# Railway configuration for monorepo deployment

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node backend/server.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
